name: Generate Pacman Contribution Game

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: Ayush-nain  # <-- replace with your username
          outputs: |
            dist/github-contribution-grid-pacman.svg
      - name: Commit Pacman SVG
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add dist/github-contribution-grid-pacman.svg
          git commit -m "Update Pacman contribution graph" || echo "No changes"
          git push
